
<style type="text/css">
A         {COLOR: 000000;TEXT-DECORATION: none}
A:visited {COLOR: 000000;TEXT-DECORATION: none}
A:active  {COLOR: 000000;TEXT-DECORATION: none}
A:hover   {COLOR: e4e4e5;TEXT-DECORATION: none}
A:link    {TEXT-DECORATION: none}
BODY      {SCROLLBAR-HIGHLIGHT-COLOR: #C0C0C0; 
   	   SCROLLBAR-SHADOW-COLOR: #C0C0C0; 
	   SCROLLBAR-ARROW-COLOR: #C0C0C0; 

	   SCROLLBAR-FACE-COLOR: #F4F4F4;
	   SCROLLBAR-3DLIGHT-COLOR: #EFEFEF;
	   SCROLLBAR-TRACK-COLOR: #EFEFEF;
	   SCROLLBAR-DARKSHADOW-COLOR: #EFEFEF}
</style>